# Файл docker-compose.yml
version: '3'

volumes:
  pg_data:
  static:
  media:

networks:
  foodgram-network:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - foodgram-network

  backend:
    image: homadoma/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media/
    networks:
      - foodgram-network

  frontend:
    env_file: .env
    image: homadoma/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    networks:
      - foodgram-network

  infra:

    image: homadoma/foodgram_infra
    env_file: .env
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/staticfiles
      - media:/app/media
    networks:
      - foodgram-network