# Generated by Django 3.2.16 on 2024-09-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240905_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientsrecipies',
            old_name='quantity',
            new_name='amount',
        ),
    ]
