# Generated by Django 3.2.16 on 2024-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_quantity_ingredientsrecipies_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipies',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientsRecipies', to='recipes.Ingredients', verbose_name='Ингредиент'),
        ),
    ]
