# Generated by Django 3.2.16 on 2024-09-08 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientsrecipies',
            options={'verbose_name': 'Количество ингридиента', 'verbose_name_plural': 'Количество ингридиентов'},
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='measurement_unit',
            field=models.CharField(max_length=60, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredientsrecipies',
            name='amount',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Добавьте ингредиенты')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientsRecipies', to='recipes.Ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipies',
            name='tags',
            field=models.ManyToManyField(to='recipes.Tags', verbose_name='Тег'),
        ),
    ]
