# Generated by Django 3.2.16 on 2024-09-15 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0004_auto_20240916_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipies',
            name='is_favorite',
            field=models.ManyToManyField(related_name='favorites_recipies', through='recipes.Favorites', to=settings.AUTH_USER_MODEL, verbose_name='Избранный'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='recipes.recipies', verbose_name='Рецепт'),
        ),
    ]
