# Generated by Django 3.2.16 on 2024-09-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20240916_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipies',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
    ]
