# Generated by Django 3.2.16 on 2024-08-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='media/users/', verbose_name='Аватар'),
        ),
    ]
